site_name: Global CS
site_author: 'Global-CS-application'
theme:   

  name: material
  palette:
    primary: lime

nav:
  - "index.md"
  - 项目介绍:
      - T0:
        - ETH MSCS: "Program/T0/ETH MSCS.md"
        - EPFL MSCS: "Program/T0/EPFL MSCS.md"
      - T0.5:
          - Cambridge ACS Mphil: "Program/T0.5/Cambridge ACS Mphil.md"
          - Oxford ACS Mphil: "Program/T0.5/Oxford ACS Mphil.md"
      - T1:
          - KTH MSML: "Program/T1/KTH MSML.md"
          - KTH MSCS: "Program/T1/KTH MSCS.md"
          - TUD MSCS: "Program/T1/TUD MSCS.md"